In [ ]:
#What is NumPy, and why is it widely used in Python?
#sol= NumPy (Numerical Python) is a library for working with arrays and mathematical operations in Python. It is a fundamental package for scientific computing and data analysis in Python.
#NumPy is widely used in Python for several reasons:
#Efficient numerical computations: NumPy's vectorized operations and high-performance mathematical functions make it an ideal choice for numerical computations.
#Easy data manipulation: NumPy's multi-dimensional arrays and indexing features make it easy to manipulate and analyze data.
#Integration with other libraries: NumPy is integrated with other popular Python libraries, such as Pandas, SciPy, and Matplotlib, making it a fundamental package for scientific computing and data analysis.
#Example:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
# Perform element-wise addition
result = arr1 + arr2
print(result)  # Output: [ 7  9 11 13 15]
#How does broadcasting work in NumPy?
#Sol= Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays with different shapes and sizes. It's a way to align arrays with different shapes so that they can be operated on element-wise.
#Shape Comparison: When you try to perform an operation on two arrays, NumPy compares their shapes to determine if they can be broadcasted.
#Broadcasting Rules: NumPy follows a set of broadcasting rules to determine how to align the arrays
Example 1: Adding a scalar to an array

import numpy as np

arr = np.array([1, 2, 3])
scalar = 2

result = arr + scalar
print(result)  # [3, 4, 5]

In this example, the scalar 2 is broadcasted to match the shape of the array arr.
#What is a Pandas DataFrame?
#sol= A Pandas DataFrame is a two-dimensional table of data with rows and columns, similar to an Excel spreadsheet or a table in a relational database. It consists of:

- Rows (index): Representing individual observations or records
- Columns: Representing variables or fields of data
- Data: Stored in a table format, allowing for efficient data manipulation and analysis.
#Explain the use of the groupby() method in Pandas?
#sol= groupby() method in Pandas is used to split a DataFrame into groups based on one or more columns, and then apply various aggregation functions to each group.
df.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False)
#we have a DataFrame df with columns Name, Age, and Country:

   Name  Age Country
0   John   25    USA
1   Jane   30    UK
2   John   25    USA
3   Jane   30    UK
4   Bob    35    Canada

We can group by Country and calculate the mean Age for each group:

grouped_df = df.groupby('Country')['Age'].mean()
print(grouped_df)
#Output:

Country
Canada    35.0
UK        30.0
USA       25.0
Name: Age, dtype: float64
#1. groupby().apply(): Apply a custom function to each group.
2. groupby().transform(): Apply a function to each group and return a transformed DataFrame.
3. groupby().filter(): Filter the DataFrame based on a condition applied to each group.
#Why is Seaborn preferred for statistical visualizations?
#sol=Seaborn is a popular data visualization library in Python, built on top of Matplotlib. It is preferred for statistical visualizations for several reasons
#Statistical Visualization

1. Integrated statistical analysis: Seaborn integrates well with statistical analysis libraries like Pandas, Scikit-learn, and Statsmodels.
2. Built-in statistical visualization tools: Seaborn provides a range of statistical visualization tools, such as regression plots, box plots, and violin plots.
#What are the differences between NumPy arrays and Python lists?
#sol=NumPy arrays and Python lists are both data structures used to store collections of data, but they have distinct differences in terms of their characteristics, advantages, and use cases.
#- omogeneity: NumPy arrays are homogeneous (same data type), while Python lists are heterogeneous (different data types).
- Memory usage: NumPy arrays are more memory-efficient.
- Performance: NumPy arrays are optimized for numerical computations, making them faster.
- Indexing and slicing: NumPy arrays support advanced indexing and slicing.
- Mathematical operations: NumPy arrays support element-wise mathematical operations.

Use NumPy arrays for numerical computations and Python lists for general-purpose programming and storing non-numerical data.
#What is a heatmap, and when should it be used?
#sol=  heatmap is a graphical representation of data where values are depicted by color. It is used to:

- Visualize complex data relationships
- Show patterns, trends, and correlations
- Highlight outliers and anomalies

Use heatmaps when:

- Analyzing large datasets
- Visualizing relationships between multiple variables
- Identifying clusters, patterns, or hotspots in data
#What does the term “vectorized operation” mean in NumPy?
#sol= n NumPy, a "vectorized operation" refers to an operation that is applied element-wise to entire arrays or vectors at once, without the need for explicit loops.

Example: a = np.array([1, 2, 3]); b = np.array([4, 5, 6]); result = a + b

In this example, the addition operation is applied element-wise to the entire arrays a and b, resulting in a new array result. This is a vectorized operation
#How does Matplotlib differ from Plotly?
#sol =Matplotlib and Plotly are two popular data visualization libraries in Python. Here's a brief comparison:

#Matplotlib

1. Static plots: Matplotlib creates static, 2D plots.
2. Wide range of plot types: Supports various plot types, including line plots, scatter plots, histograms, and more.
3. Customizable: Highly customizable, with extensive options for colors, fonts, labels, and more.
4. Integration with other libraries: Easily integrates with other popular libraries like NumPy, Pandas, and Scikit-learn.

#Plotly

1. Interactive plots: Plotly creates interactive, web-based visualizations.
2. 3D plots: Supports 3D plots, in addition to 2D plots.
3. Animation: Allows for animated plots, making it ideal for visualizing time-series data.
4. User-friendly interface: Offers a user-friendly interface for customizing plots, with tools like zooming, hovering, and clicking.

Key differences

1. Interactivity: Plotly offers interactive plots, while Matplotlib creates static plots.
2. Dimensionality: Plotly supports 3D plots, while Matplotlib is limited to 2D plots.
3. Animation: Plotly allows for animated plots, while Matplotlib does not.
#What is the significance of hierarchical indexing in Pandas?
#sol=Hierarchical indexing (also known as MultiIndex) in Pandas allows you to:

1. Organize data with multiple levels: Create a table with multiple indices, enabling efficient querying and manipulation of data.
2. Efficient data retrieval: Quickly access specific data subsets using label-based indexing.
3. Improved data analysis: Simplify complex data analysis tasks, such as grouping, sorting, and aggregating data.

Hierarchical indexing is particularly useful when working with:

1. Time-series data
2. Panel data (e.g., stock prices)
3. Data with multiple categories or labels

It enables you to easily manipulate and analyze data with multiple dimensions, making it a powerful feature in Pandas.
# What is the role of Seaborn’s pairplot() function?
#sol=Seaborn's pairplot() function creates a matrix of pairwise relationships between variables in a dataset, displaying:

1. Scatterplots: for continuous variables
2. Boxplots: for continuous vs. categorical variables
3. Bar plots: for categorical variables

pairplot() helps to:

1. Visualize correlations between variables
2. Identify patterns and relationships
3. Explore dataset distributions and structure

It's a useful tool for exploratory data analysis (EDA) and data visualization.
#What is the purpose of the describe() function in Pandas?
#sol= The describe() function in Pandas generates descriptive statistics for a DataFrame or Series, including:

1. Count
2. Mean
3. Standard Deviation
4. Minimum
5. 25% (Q1)
6. 50% (Median)
7. 75% (Q3)
8. Maximum

It provides a quick summary of the central tendency, dispersion, and distribution of the data, helping with:

1. Data exploration
2. Data cleaning
3. Statistical analysis
#Why is handling missing data important in Pandas?
#Handling missing data is important in Pandas because:

1. Biased results: Missing data can lead to biased or incorrect results in analysis and modeling.
2. Data quality issues: Missing data can indicate data quality issues, such as data entry errors or incomplete data collection.
3. Model performance: Missing data can negatively impact the performance of machine learning models.

Pandas provides various methods to handle missing data, including:

1. Dropping missing values: dropna()
2. Filling missing values: fillna()
3. Imputing missing values: interpolate() or SimpleImputer from Scikit-learn.
#What are the benefits of using Plotly for data visualization?
#sol= The benefits of using Plotly for data visualization include:

1. Interactive Visualizations: Plotly creates interactive, web-based visualizations that allow users to hover, zoom, and pan.
2. 3D and Animated Plots: Plotly supports 3D plots, animations, and videos, making it ideal for visualizing complex data.
3. Multiple Plot Types: Plotly offers a wide range of plot types, including line plots, scatter plots, bar charts, histograms, and more.
4. Customizable: Plotly allows for extensive customization of plot appearance, including colors, fonts, labels, and more.
5. Integration with Other Libraries: Plotly integrates seamlessly with popular libraries like Pandas, NumPy, and Scikit-learn.
6. Web-Based Sharing: Plotly visualizations can be easily shared online, making it simple to collaborate with others.
7. Large Dataset Handling: Plotly can handle large datasets and performs well even with millions of data points.
#How does NumPy handle multidimensional arrays?
#sol= NumPy handles multidimensional arrays using the following key concepts:

1. ndarray: The core data structure in NumPy, representing a multidimensional array.
2. Dimensions: Specified by the shape attribute (e.g., (3, 4) for a 3x4 array).
3. Axes: Each dimension is associated with an axis (e.g., rows and columns in a 2D array).
4. Indexing: Accessing elements using integer or slice indexing (e.g., arr[1, 2]).
5. Slicing: Extracting subsets of the array using slice notation (e.g., arr[1:3, 1:3]).
6. Reshaping: Changing the shape of an array without modifying its data (e.g., arr.reshape((4, 3))).
7. Broadcasting: Performing operations on arrays with different shapes by aligning them according to their broadcasting rules.
#What is the role of Bokeh in data visualization?
#sol=Bokeh is a Python library for interactive data visualization. Its role is to:

1. Create web-based interactive plots: Bokeh generates HTML plots that can be viewed in web browsers.
2. Provide high-level API: Bokeh offers a simple, intuitive API for creating plots, making it accessible to users without extensive programming experience.
3. Support for large datasets: Bokeh can handle large datasets and provides tools for optimizing performance.
4. Customizable and extensible: Bokeh allows users to customize plot appearance and behavior, and provides a plugin architecture for extending its capabilities.
5. Integrate with other libraries: Bokeh integrates well with popular libraries like Pandas, NumPy, and Scikit-learn.
#Explain the difference between apply() and map() in Pandas?
#sol=In Pandas, apply() and map() are both used to perform element-wise operations on Series or DataFrames. The key differences are:

Apply()

1. Flexible: Can apply any function, including custom functions, to each element or row/column.
2. Row-wise or column-wise: Can be applied to rows (axis=1) or columns (axis=0).
3. Returns a Series or DataFrame: Depending on the input and function applied.

Map()

1. Dictionary-based: Requires a dictionary or a function that takes one argument.
2. Element-wise: Applies the function to each element of the Series.
3. Returns a Series: Always returns a Series, even if the input is a DataFrame.
#What are some advanced features of NumPy?
#sol=Some advanced features of NumPy include:

1. Broadcasting: Allows operations on arrays with different shapes and sizes.
2. Vectorized Operations: Enables element-wise operations on entire arrays, eliminating the need for loops.
3. Advanced Indexing: Supports indexing with arrays, slices, and boolean masks.
4. Linear Algebra Functions: Provides an extensive set of linear algebra functions, including eigenvalue decomposition and singular value decomposition.
5. Random Number Generation: Offers a range of random number generators, including uniform, normal, and binomial distributions.
6. Polynomial Functions: Supports polynomial operations, including evaluation, differentiation, and integration.
7. FFT (Fast Fourier Transform) Functions: Enables efficient computation of discrete Fourier transforms.
8. Matrix Operations: Provides functions for matrix multiplication, matrix inverse, and matrix determinant.
9. Data Type Manipulation: Allows conversion between different data types, including integer, floating-point, and complex numbers.
10. Memory Management: Offers functions for managing memory, including array allocation, deallocation, and copying.
#How does Pandas simplify time series analysis?
#sol=Pandas simplifies time series analysis in several ways:

1. Timestamp Indexing: Pandas allows you to create a timestamp index, making it easy to perform time-based operations.
2. Date and Time Functions: Pandas provides various date and time functions, such as to_period(), resample(), and rolling(), to manipulate and analyze time series data.
3. Time Series Resampling: Pandas enables resampling of time series data to different frequencies, such as from daily to monthly or quarterly.
4. Rolling Window Calculations: Pandas allows you to perform rolling window calculations, such as moving averages or standard deviations, on time series data.
5. Time Zone Handling: Pandas provides built-in support for handling time zones, making it easy to work with data from different regions.
6. Integration with Other Libraries: Pandas integrates seamlessly with other popular libraries, such as NumPy, Matplotlib, and Scikit-learn, making it easy to incorporate time series analysis into larger workflows.
7. Data Alignment and Merging: Pandas provides efficient data alignment and merging capabilities, making it easy to combine time series data from different sources.
8. Handling Missing Data: Pandas offers various options for handling missing data in time series, including interpolation, imputation, and padding.
#What is the role of a pivot table in Pandas?
#sol= Pandas, a pivot table is a data summarization tool that helps to:

1. Aggregate data: Group data by one or more columns and perform aggregation operations (e.g., sum, mean, count).
2. Rotate data: Transform data from a long format to a wide format, making it easier to analyze and visualize.
3. Create custom data views: Generate a customized view of the data by selecting specific columns, rows, and aggregation functions.

Pivot tables are useful for:

1. Data analysis: Quickly summarize and explore large datasets.
2. Data visualization: Prepare data for visualization by aggregating and rotating it.
3. Reporting: Generate customized reports by creating pivot tables with specific data views.

In Pandas, you can create a pivot table using the pivot_table() function, which takes in parameters such as the data, index, columns, values, and aggregation function.
#Why is NumPy’s array slicing faster than Python’s list slicing?
#sol=NumPy's array slicing is faster than Python's list slicing for several reasons:

1. Vectorized operations: NumPy arrays are designed for vectorized operations, which means that operations are applied to the entire array at once, rather than iterating over individual elements.

2. Memory layout: NumPy arrays store data in a contiguous block of memory, allowing for efficient access and manipulation of elements.

3. Striding: NumPy arrays use a concept called striding, which allows for efficient access to elements by skipping over memory locations.

4. Pre-allocated memory: When slicing a NumPy array, a new array object is created, but the underlying memory is not copied. Instead, the new array object points to the same memory location as the original array.

5. Optimized C code: NumPy's array slicing is implemented in optimized C code, which provides a significant performance boost compared to Python's list slicing.

In contrast, Python's list slicing involves:

1. Iterating over elements: List slicing involves iterating over individual elements, which can be slower than NumPy's vectorized operations.

2. Creating a new list: When slicing a list, a new list object is created, and the elements are copied from the original list to the new list.

3. Dynamic memory allocation: Lists in Python are dynamic data structures, which means that memory is allocated and deallocated as elements are added or removed. This can lead to slower performance compared to NumPy's pre-allocated memory.
#What are some common use cases for Seaborn?
#sol=Seaborn is a popular data visualization library in Python, built on top of Matplotlib. Some common use cases for Seaborn include:

Exploratory Data Analysis

1. Visualizing distributions: Seaborn's distplot() and kdeplot() functions help visualize distributions of continuous variables.
2. Scatterplots and regression: Seaborn's lmplot() and regplot() functions create informative scatterplots with regression lines.

Categorical Data Visualization

1. Bar plots and count plots: Seaborn's barplot() and countplot() functions create informative bar plots and count plots for categorical data.
2. Box plots and violin plots: Seaborn's boxplot() and violinplot() functions create informative box plots and violin plots for comparing distributions across categories.

Heatmaps and Clustered Heatmaps

1. Visualizing correlation matrices: Seaborn's heatmap() function creates informative heatmaps for visualizing correlation matrices.
2. Clustered heatmaps: Seaborn's clustermap() function creates clustered heatmaps for visualizing complex data structures.

Customization and Integration

1. Customizing plot appearance: Seaborn provides various options for customizing plot appearance, including colors, fonts, and labels.
2. Integrating with other libraries: Seaborn integrates seamlessly with other popular libraries, including Pandas, NumPy, and Matplotlib.

                                        Practical Question
#How do you create a 2D NumPy array and calculate the sum of each row?
#sol=# Import the NumPy library
import numpy as np

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the 2D array
print("2D Array:")
print(array_2d)

# Calculate the sum of each row
row_sums = np.sum(array_2d, axis=1)

# Print the sum of each row
print("\nSum of each row:")
print(row_sums)


Output:


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of each row:
[6 15 24]
#Write a Pandas script to find the mean of a specific column in a DataFrame?
## Import the Pandas library
import pandas as pd

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85, 90, 78, 92]
}
df = pd.DataFrame(data)

# Print the original DataFrame
print("Original DataFrame:")
print(df)

# Calculate the mean of the 'Score' column
mean_score = df['Score'].mean()

# Print the mean of the 'Score' column
print("\nMean of the 'Score' column:")
print(mean_score)


Output:


Original DataFrame:
     Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   40     92

Mean of the 'Score' column:
86.25
In this script:

1. We import the Pandas library.
2. We create a sample DataFrame with columns 'Name', 'Age', and 'Score'.
3. We print the original DataFrame to verify its contents.
4. We calculate the mean of the 'Score' column using the mean() method.
5. We print the mean of the 'Score' column to verify the result.
#Create a scatter plot using Matplotlib?
#sol= Matplotlib:


# Import the Matplotlib library
import matplotlib.pyplot as plt

# Import the NumPy library for generating sample data
import numpy as np

# Generate sample data
x = np.random.rand(50)
y = np.random.rand(50)

# Create the scatter plot
plt.scatter(x, y)

# Set title and labels
plt.title('Scatter Plot Example')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Display the plot
plt.show()


This code will generate a scatter plot with 50 random points.

To customize the plot further, you can use various options available in the scatter() function, such as:

- marker: Specify the marker type (e.g., 'o', '^', 's').
- c: Specify the color of the markers.
- s: Specify the size of the markers.
- alpha: Specify the transparency of the markers.

For example:


plt.scatter(x, y, marker='^', c='red', s=100, alpha=0.5)
#How do you calculate the correlation matrix using Seaborn and visualize it with a heatmap?
#sol=Seaborn and visualize it with a heatmap:


# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Generate sample data
np.random.seed(0)
data = np.random.multivariate_normal([0, 0, 0], [[1, 0.8, 0.2], [0.8, 1, 0.5], [0.2, 0.5, 1]], 100)
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3'])

# Calculate the correlation matrix
corr_matrix = df.corr()

# Create a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', square=True)
plt.title('Correlation Matrix')
plt.show()


This code will generate a heatmap showing the correlation matrix of the sample data.
#Generate a bar plot using Plotly?
#sol=Here's an example code to generate a bar plot using Plotly:


# Import the Plotly library
import plotly.graph_objects as go

# Define the data
categories = ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries']
values = [20, 14, 23, 18, 12]

# Create the bar plot
fig = go.Figure(data=[go.Bar(x=categories, y=values)])

# Customize the plot
fig.update_layout(
    title='Fruit Quantities',
    xaxis_title='Fruit',
    yaxis_title='Quantity'
)

# Display the plot
fig.show()


This code will generate a bar plot showing the quantities of different fruits.
#Create a DataFrame and add a new column based on an existing column?
#sol= Import the Pandas library
import pandas as pd

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85, 90, 78, 92]
}
df = pd.DataFrame(data)

# Print the original DataFrame
print("Original DataFrame:")
print(df)

# Add a new column 'Grade' based on the 'Score' column
df['Grade'] = pd.cut(df['Score'], bins=[0, 70, 85, 100], labels=['F', 'C', 'A'], include_lowest=True)

# Print the updated DataFrame
print("\nUpdated DataFrame with 'Grade' column:")
print(df)


Output:


Original DataFrame:
     Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   40     92

Updated DataFrame with 'Grade' column:
     Name  Age  Score Grade
0    Alice   25     85     A
1      Bob   30     90     A
2  Charlie   35     78     C
3    David   40     92     A
#Write a program to perform element-wise multiplication of two NumPy arrays?
#sol=Import the NumPy library
import numpy as np

# Create two sample NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Print the original arrays
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Perform element-wise multiplication
result = np.multiply(array1, array2)

# Print the result
print("\nResult of element-wise multiplication:")
print(result)


Output:


Array 1:
[1 2 3 4 5]

Array 2:
[ 6  7  8  9 10]

Result of element-wise multiplication:
[ 6 14 24 36 50]
#Create a line plot with multiple lines using Matplotlib?
#sol=Matplotlib:


# Import the Matplotlib library
import matplotlib.pyplot as plt

# Import the NumPy library for generating sample data
import numpy as np

# Generate sample data
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = np.sin(2*x)

# Create the line plot
plt.plot(x, y1, label='sin(x)')
plt.plot(x, y2, label='cos(x)')
plt.plot(x, y3, label='sin(2x)')

# Customize the plot
plt.title('Line Plot with Multiple Lines')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)

# Display the plot
plt.show()


This code will generate a line plot with three lines representing the functions sin(x), cos(x), and sin(2x).
#Generate a Pandas DataFrame and filter rows where a column value is greater than a threshold?
#sol=# Import the Pandas library
import pandas as pd

# Generate a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
    'Age': [25, 30, 35, 40, 45],
    'Score': [85, 90, 78, 92, 88]
}
df = pd.DataFrame(data)

# Print the original DataFrame
print("Original DataFrame:")
print(df)

# Define the threshold
threshold = 90

# Filter rows where the 'Score' column value is greater than the threshold
filtered_df = df[df['Score'] > threshold]

# Print the filtered DataFrame
print("\nFiltered DataFrame (Score > {}):".format(threshold))
print(filtered_df)


Output:


Original DataFrame:
     Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     78
3    David   40     92
4    Emily   45     88

Filtered DataFrame (Score > 90):
   Name  Age  Score
1   Bob   30     90
3  David   40     92
#Create a histogram using Seaborn to visualize a distribution?
#sol=# Import necessary libraries
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Generate sample data
np.random.seed(0)
data = np.random.randn(1000)

# Create a histogram
plt.figure(figsize=(8, 6))
sns.histplot(data, bins=30, kde=True)

# Customize the plot
plt.title('Histogram of Random Data')
plt.xlabel('Value')
plt.ylabel('Frequency')

# Display the plot
plt.show()


This code will generate a histogram with a kernel density estimate (KDE) to visualize the distribution of the sample data.
#Perform matrix multiplication using NumPy?
#sol=# Import the NumPy library
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Print the matrices
print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)

# Perform matrix multiplication
result = np.matmul(matrix_a, matrix_b)

# Print the result
print("\nResult of Matrix Multiplication:")
print(result)


Output:


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of Matrix Multiplication:
[[19 22]
 [43 50]]
#Use Pandas to load a CSV file and display its first 5 rows?
#sol=Import the Pandas library
import pandas as pd

# Specify the path to the CSV file
csv_file_path = 'data.csv'

# Load the CSV file into a Pandas DataFrame
try:
    df = pd.read_csv(csv_file_path)
    print("CSV file loaded successfully.")
except FileNotFoundError:
    print("The specified CSV file was not found.")
except pd.errors.EmptyDataError:
    print("The specified CSV file is empty.")
except pd.errors.ParserError:
    print("An error occurred while parsing the CSV file.")

# Display the first 5 rows of the DataFrame
if 'df' in locals():
    print("\nFirst 5 rows of the DataFrame:")
    print(df.head(5))
    #Create a 3D scatter plot using Plotly?
    #sol=# Import the Plotly library
import plotly.graph_objects as go

# Import the NumPy library for generating sample data
import numpy as np

# Generate sample data
np.random.seed(0)
x = np.random.randn(100)
y = np.random.randn(100)
z = np.random.randn(100)

# Create a 3D scatter plot
fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z, mode='markers')])

# Customize the plot
fig.update_layout(
    title='3D Scatter Plot',
    scene = dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='Z'
    )
)

# Display the plot
fig.show()


This code will generate a 3D scatter plot with 100 random points.











